inherit:
  - naming-restrict-live
  - git-2
  - html
  - css

allFiles:
  html:
    outline: false
  md:
    valid: true
  files:
    maxSize: 250
    maxWidth: 2500
    maxHeight: 2500
    smushed: true

files:
  - directory: 'images'
