module.exports = [
  /(^|[\/\\])\../,
  '*.html',
  'patterns/brand',
  'patterns/brand/*',
  'patterns/grid',
  'patterns/grid/*',
  'patterns/icons',
  'patterns/icons/*',
  'patterns/modules',
  'patterns/modules/*',
  'patterns/typography',
  'patterns/typography/*',
  // Jekyll folders
  '_site',
  '_site/*',
  '_layouts',
  '_layouts/*',
  '_includes',
  '_includes/*',
  '_data',
  '_data/*',
  '_posts',
  '_posts/*',
];
